name: Code Coverage

on: 
 pull_request:
  branches:
   - main

jobs:
 coverage: 
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
      python-version: 3.8

   - name: Install dependencies
     run: pip install -r requirements.txt

   - name: Upload coverage  report
     if: success()
     uses: codecov/codecov-action@v2
     with:
      token: ${{ secrets.CODECOV-TOKEN }}
